deployment:
  tasks:
    - export DEPLOYPATH=/home/t49403/public_html/ufeapp/
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R f_cekotp.php $DEPLOYPATH
    - /bin/cp -R f_login.php $DEPLOYPATH
    - /bin/cp -R post_notif.php $DEPLOYPATH
    - /bin/cp -R confirmer_post.php $DEPLOYPATH
    - /bin/cp -R confirmer.php $DEPLOYPATH
    - /bin/cp -R helper.php $DEPLOYPATH
    - /bin/cp -R reading_advert.php $DEPLOYPATH
    - /bin/cp -R tambah_advert.php $DEPLOYPATH
    - /bin/cp -R delete_advert.php $DEPLOYPATH
    - /bin/cp -R f_getactualite1.php $DEPLOYPATH
    - /bin/cp -R f_getactualite1member.php $DEPLOYPATH
    - /bin/cp -R f_getactualite2member.php $DEPLOYPATH
    - /bin/cp -R f_getactualite2.php $DEPLOYPATH
    - /bin/cp -R f_getdemar1tree.php $DEPLOYPATH
    - /bin/cp -R f_getdemar1.php $DEPLOYPATH
    - /bin/cp -R get_advert_category.php $DEPLOYPATH
    - /bin/cp -R get_tulisan.php $DEPLOYPATH
    - /bin/cp -R get_menu_bawah.php $DEPLOYPATH
    